import Mathlib.LinearAlgebra.Dimension.Constructions
import Mathlib.LinearAlgebra.Dimension.Finite

/-!
# Finite-rank obstruction for prime-orbit length models

This file formalizes the linear-algebraic core of the obstruction: if every
closed-orbit length is an integer-weighted sum of a finite list of local
lengths, all such lengths lie in a finite-dimensional rational span.  Hence a
family of `E + 1` rationally independent target lengths cannot be realized
using only `E` local lengths.

The separate arithmetic input that the real numbers `Real.log p`, indexed by
the primes, are linearly independent over `ℚ` follows from unique
factorization after clearing denominators and exponentiating.
-/

open scoped BigOperators

noncomputable section

namespace RiemannPrimeResolvent

variable {𝕜 V : Type*} [Field 𝕜] [AddCommGroup V] [Module 𝕜 V]

/-- An integer-weighted cycle length belongs to the span of the local edge
lengths. -/
theorem weightedCycle_mem_span {E : ℕ} (ell : Fin E → V) (counts : Fin E → ℕ) :
    (∑ e, (counts e : 𝕜) • ell e) ∈ Submodule.span 𝕜 (Set.range ell) := by
  apply Submodule.sum_mem
  intro e _
  exact Submodule.smul_mem _ _
    (Submodule.subset_span (Set.mem_range_self e))

/-- The rational (or field-valued) span generated by `E` local lengths has
dimension at most `E`. -/
theorem cycleLengthSpan_finrank_le {E : ℕ} (ell : Fin E → V) :
    (Set.range ell).finrank 𝕜 ≤ E := by
  simpa using (finrank_range_le_card (R := 𝕜) ell)

/-- `E` local lengths cannot contain `E + 1` linearly independent target
lengths in their span. -/
theorem no_fin_succ_independent_in_cycleSpan {E : ℕ} (ell : Fin E → V)
    (target : Fin (E + 1) → V) (htarget : LinearIndependent 𝕜 target)
    (hmem : ∀ i, target i ∈ Submodule.span 𝕜 (Set.range ell)) : False := by
  let W : Submodule 𝕜 V := Submodule.span 𝕜 (Set.range ell)
  letI : Module.Finite 𝕜 W := by
    dsimp [W]
    exact Module.Finite.span_of_finite 𝕜 (Set.finite_range ell)
  let lifted : Fin (E + 1) → W := fun i => ⟨target i, hmem i⟩
  have hlifted : LinearIndependent 𝕜 lifted := by
    apply LinearIndependent.of_comp W.subtype
    simpa [lifted, W, Function.comp_def] using htarget
  have hlarge : E + 1 ≤ Module.finrank 𝕜 W := by
    simpa using hlifted.fintype_card_le_finrank
  have hsmall : Module.finrank 𝕜 W ≤ E := by
    simpa [W, Set.finrank] using cycleLengthSpan_finrank_le (𝕜 := 𝕜) ell
  omega

end RiemannPrimeResolvent
