/-
Copyright (c) 2026 Lluís Eriksson.
Released under the GNU Affero General Public License v3.0.
-/

import Mathlib

/-!
# Scalar rate optimization

This module records the proposed exponent
`min ((2q - 1)/3) (2/3)`.  It is independent of the unproved spectral input.
-/

namespace RiemannPrimeResolvent

/-- Candidate optimized decay exponent generated by a spectral defect rate `q`. -/
noncomputable def rateExponent (q : ℝ) : ℝ :=
  min ((2 * q - 1) / 3) (2 / 3)

/-- Any spectral exponent strictly larger than `1/2` yields positive decay. -/
theorem rateExponent_pos {q : ℝ} (hq : 1 / 2 < q) :
    0 < rateExponent q := by
  rw [rateExponent, lt_min_iff]
  constructor
  · linarith
  · norm_num

/-- The proposed rate never exceeds the prolate/prime ceiling `2/3`. -/
theorem rateExponent_le_two_thirds (q : ℝ) :
    rateExponent q ≤ 2 / 3 :=
  min_le_right _ _

/-- Above the threshold `q = 3/2`, the rate saturates at `2/3`. -/
theorem rateExponent_eq_two_thirds {q : ℝ} (hq : 3 / 2 ≤ q) :
    rateExponent q = 2 / 3 := by
  rw [rateExponent, min_eq_right]
  linarith

/-- Below the threshold `q = 3/2`, the spectral exponent is the active term. -/
theorem rateExponent_eq_spectral {q : ℝ} (hq : q ≤ 3 / 2) :
    rateExponent q = (2 * q - 1) / 3 := by
  rw [rateExponent, min_eq_left]
  linarith

end RiemannPrimeResolvent
