import OnePointResolvent

/-! Axiom audit entry point: `lake env lean OnePointResolvent/Oracle.lean`. -/

#print axioms OnePointResolvent.hausdorffDiff_zero
#print axioms OnePointResolvent.hausdorffDiff_succ
#print axioms OnePointResolvent.hausdorffDiff_atomicMoment
#print axioms OnePointResolvent.atomicMoment_isHausdorffCompletelyMonotone
#print axioms OnePointResolvent.hausdorffDiff_atomicMoment_nonneg
#print axioms OnePointResolvent.spectrum_shift_pos
#print axioms OnePointResolvent.resolventWeight_nonneg
#print axioms OnePointResolvent.compactifiedPoint_nonneg
#print axioms OnePointResolvent.compactifiedPoint_le_one
#print axioms OnePointResolvent.finiteResolventMoment_isHausdorffCompletelyMonotone
#print axioms OnePointResolvent.finiteResolventMoment_hausdorffDiff_nonneg
#print axioms OnePointResolvent.atomicHankelCertificate_nonneg
#print axioms OnePointResolvent.atomicLocalizingCertificate_nonneg
#print axioms OnePointResolvent.finiteResolventHankelCertificate_nonneg
#print axioms OnePointResolvent.finiteResolventLocalizingCertificate_nonneg
#print axioms OnePointResolvent.abs_sub_le_three
#print axioms OnePointResolvent.resolvent_errorBudget
#print axioms OnePointResolvent.finitePositiveStieltjesAt_nonneg
#print axioms OnePointResolvent.stieltjes_atom_norm_le_of_denominator
#print axioms OnePointResolvent.finitePositiveStieltjes_norm_le_of_denominator
#print axioms OnePointResolvent.finitePositiveStieltjes_family_norm_le_of_denominator
#print axioms OnePointResolvent.stieltjes_disk_denominator_bound
#print axioms OnePointResolvent.stieltjes_atom_norm_le_two
#print axioms OnePointResolvent.finitePositiveStieltjes_norm_le_two
#print axioms OnePointResolvent.finitePositiveStieltjes_family_norm_le_two
#print axioms OnePointResolvent.compactifiedPoint_pos
#print axioms OnePointResolvent.stieltjesCompactifiedDenominator_ne_zero
#print axioms OnePointResolvent.stieltjes_compactified_denominator_identity
#print axioms OnePointResolvent.stieltjes_compactified_denominator_norm_identity
#print axioms OnePointResolvent.stieltjes_compactified_denominator_cross_identity
#print axioms OnePointResolvent.stieltjes_denominator_bound_of_compactified
#print axioms OnePointResolvent.exists_stieltjesCompactifiedDenominator_lower_bound
#print axioms OnePointResolvent.exists_stieltjes_denominator_bound_on_compact
#print axioms OnePointResolvent.exists_finitePositiveStieltjes_family_bound_on_compact
#print axioms OnePointResolvent.resolventTransform_finitePositiveStieltjesMeasure
#print axioms OnePointResolvent.compactifiedStieltjesWeight_nonneg
#print axioms OnePointResolvent.compactifiedStieltjesFiniteMeasure_mass_eq
#print axioms OnePointResolvent.compactifiedStieltjesFiniteMeasure_compl_Icc_eq_zero
#print axioms OnePointResolvent.compactifiedStieltjesFiniteMeasure_mem_family
#print axioms OnePointResolvent.isCompact_compactifiedStieltjesMeasureFamily
#print axioms OnePointResolvent.range_compactifiedStieltjesFiniteMeasure_subset_family
#print axioms OnePointResolvent.isCompact_closure_range_compactifiedStieltjesFiniteMeasure
